name: Event Send

on:
  push:
    branches:
      - main
      - feature/*
      - enhancement/*
      - bugfix/*
      - hotfix/*
      - release/*
      - test/*
      - refactor/*
      - ci/*
      - style/*
      - docs/*
  pull_request:
    branches:
      - main
      
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get commit msg
        if: github.event_name == 'push'
        id: commit
        run: |
          echo "COMMIT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV
          echo "COMMIT_FULL_HASH=$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --pretty=format:'%ad')" >> $GITHUB_ENV
          echo "COMMIT_SUBJECT=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMIT_BODY=$(git log -1 --pretty=format:'%b')" >> $GITHUB_ENV
          echo "COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV

      - name: Send commit to discord
        if: github.event_name == 'push'
        continue-on-error: true
        run: |
          curl -f -X POST "${{ secrets.BOT_URL }}" \
          -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
          -F "hash=$COMMIT_HASH" \
          -F "full_hash=$COMMIT_FULL_HASH" \
          -F "author_name=$COMMIT_AUTHOR_NAME" \
          -F "author_email=$COMMIT_AUTHOR_EMAIL" \
          -F "date=$COMMIT_DATE" \
          -F "subject=$COMMIT_SUBJECT" \
          -F "body=$COMMIT_BODY" \
          -F "branch=$COMMIT_BRANCH" \
          -F "event_name=$EVENT_NAME"

